### ISSUE TITLE
Website generally slow, freezes on any user action and over time

### ISSUE THREAD

**Issue by DominicF96** [0xa3k5/token-icons#11]
Hello again!

**Summary:**

The TokenIcons.io website is experiencing significant performance issues, including general slowness and frequent freezing during user interactions. Icons also stop loading after ~30 rows, website stops responding after ~5 seconds.

**Steps to Reproduce:**

1. Navigate to [TokenIcons.io](https://tokenicons.io/).
2. Attempt any user action, such as attempting to search, switch between Token/Network icons, switch between Mono/Branded icons,  etc.
3. Observe the website's responsiveness.

**Expected Result:**

The website should respond quickly and smoothly to user actions without any noticeable delays or freezes.

**Actual Result:**

- The website loads slowly.
- Any user action results in the website freezing completely.
- Sometimes the website becomes completely unresponsive, requiring a page refresh.

**Severity:**

Low-Moderate; I personally mostly use token-icons as an NPM package, but tokenicons.io is a useful tool to see which icons are available.The Figma Plugin still works great (Congrats on 4.5k installs 👀🔥), so there is a workaround.

Browser: Chrome (Version 125.0.6422.76),
Operating System: Windows 11

**Comment by 0xa3k5** [comment]
hey, 

I suspect this is caused by either: 

- a bug on the filtering & pagination logic that causes to load all of the icons at once
- something is wrong with the webpack (less likely)

I'll try to fix this, thank you for creating an issue

**Comment by Azleal** [comment]
@0xa3k5  this issue still exists. I'm using nextjs, even if there's only one network icon, it takes a long time to display the page. appreciate it if you could take look at this. thanks

**Comment by 0xa3k5** [comment]
@Azleal did you mean to mention the #25 ? This specific issue was about https://tokenicons.io for the other one, and #40 (i think related) I'm exploring a solution but I'm a bit lost tbh.

**Comment by Azleal** [comment]
hi @0xa3k5 thank you for your reply. I think #25 is pretty much the situation I'm facing. however, I neither config anything like `NextConfig.experimental.optimizePackageImports` nor `NextConfig.experimental.turbo.treeShaking` in my `next.config.ts` file. even if there's only one place using `<NetworkIcon />` the compiling process is very slow, took more than 40s or so. if I comment the `<NetworkIcon />`, finished compiling in 100ms. for now I have to leave it commented and ask for some help. this is really an awesome lib and I do appreciate your work. since #25 is closed now, I wonder if there is an active issue related to this so that I can keep an eye on it. thank you for your time

**Comment by 0xa3k5** [comment]
reopened #25 @Azleal i'm exploring a solution, might take a while.
